### ISSUE TITLE
the emergency shuttle can get stuck in transit, infinitely.

### ISSUE THREAD

**Issue by Blute1** [HippieStation/HippieStation#4884] opened 2017-11-18 06:19 UTC
![](https://vgy.me/vy0aDn.png)

**Comment by Blute1** [comment] 2017-11-18 06:20
Round ID #24468

**Comment by praisenarsie** [comment] 2017-11-18 14:07
looks a lot like the arrivals shuttle to me mister

**Comment by JohnGinnane** [comment] 2018-03-22 12:32
@Blute1 has this happened since you reported it?

**Comment by Carbonhell** [comment] 2018-08-07 11:30
Cannot reproduce/never happened anymore, closing

**Closed by Carbonhell** 2018-08-07 11:30 UTC
